### ISSUE TITLE
RH7 openssl-static missing, causes role to fail

### ISSUE THREAD

**Issue by thisdougb** [geerlingguy/ansible-role-ruby#40]
Running the role on a RH7.4 (AWS instance) gives:

```
TASK [geerlingguy.ruby : Install ruby and rubygems.] *************************************************************************************************
skipping: [34.242.36.252] => (item=[]) 

TASK [geerlingguy.ruby : Update apt cache.] **********************************************************************************************************
skipping: [34.242.36.252]

TASK [geerlingguy.ruby : Set rubygems package name for Ubuntu 14.04.] ********************************************************************************
skipping: [34.242.36.252]

TASK [geerlingguy.ruby : Install ruby and rubygems.] *************************************************************************************************
skipping: [34.242.36.252] => (item=[]) 

TASK [geerlingguy.ruby : Install packages required to build ruby (RedHat).] **************************************************************************
failed: [34.242.36.252] (item=[u'zlib-devel', u'openssl-static']) => {"changed": false, "failed": true, "item": ["zlib-devel", "openssl-static"], "msg": "No package matching 'openssl-static' found available, installed or updated", "rc": 126, "results": ["No package matching 'openssl-static' found available, installed or updated"]}

PLAY RECAP *******************************************************************************************************************************************
34.242.36.252              : ok=18   changed=1    unreachable=0    failed=1  
```

changing this task allows the role to complete:
```
# geerlingguy.ruby/tasks/install-from-source.yml

- name: Install packages required to build ruby (RedHat).
  yum: "name={{ item }} state=present"
  with_items:
    - zlib-devel
    - openssl-devel
#    - openssl-static
  when: ansible_os_family == 'RedHat'
```

I'm making an assumption that the -devel rpm is what ruby needs, but I'm not 100% sure that's the only (or a good) fix for this.   I think openssl-static works for RH6, but it was dropped in RH7.

cheers,
