### ISSUE TITLE
Ruby required to build Ruby from source

### ISSUE THREAD

**Issue by datenimperator** [geerlingguy/ansible-role-ruby#54]
On the `ubuntu/bionic64` Vagrant box, installing Ruby from source fails because Ruby isn't installed. #wtf I fixed this by installing the system Ruby package first, but maybe you'd like to include it into the role.

```yaml
---
- hosts: all

  tasks:
    - name: Install missing packages to ensure Ruby role succeeds
      apt:
        name:
          - git
          - ruby
        state: present

    - name: Install Ruby from source
      include_role:
        name: geerlingguy.ruby
      vars:
        ruby_install_from_source: true
        ruby_download_url: http://cache.ruby-lang.org/pub/ruby/2.5/ruby-2.5.2.tar.gz
        ruby_version: 2.5.2
```
